<?php 	
	define('HOSTNAME_DATABASE', 'mysql.zz.com.ve');
	define('USERNAME_DATABASE', 'usershop');
	define('PASSWORD_DATABASE', 'usershop_123T');
	define('NAME_DATABASE', 'efaby'); 	 
	define('URL_BASE', '/');
	define('PATH_MODELS', PATH_ROOT."/app/models");
	define('PATH_CONTROLLERS', PATH_ROOT."/app/controllers");
	define('PATH_VIEWS', PATH_ROOT."/public/views");
	define('PATH_BASE', "");	
	define('PATH_CSS', PATH_BASE."/public/web/css");
	define('PATH_JS', PATH_BASE."/public/web/js");
	define('PATH_IMAGES', PATH_BASE."/public/web/images");
	define('PATH_TEMPLATE', PATH_ROOT."/public/template");	
?>
