<?php 	
	define('HOSTNAME_DATABASE', 'localhost');
	define('USERNAME_DATABASE', 'root');
	define('PASSWORD_DATABASE', 'sistemas');
	define('NAME_DATABASE', 'shop'); 	 
	define('URL_BASE', '/shop/');
	define('PATH_MODELS', PATH_ROOT."/app/models");
	define('PATH_CONTROLLERS', PATH_ROOT."/app/controllers");
	define('PATH_VIEWS', PATH_ROOT."/public/views");
	define('PATH_BASE', "/shop");	
	define('PATH_CSS', PATH_BASE."/public/web/css");
	define('PATH_JS', PATH_BASE."/public/web/js");
	define('PATH_IMAGES', PATH_BASE."/public/web/images");
	define('PATH_TEMPLATE', PATH_ROOT."/public/template");	
?>
